apiVersion: v1
kind: Service
metadata:
  name: cloudraft-kv-store-service
spec:
  selector:
    app: cloudraft-kv-store
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 31212
